imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    # translator configuration - logging normally defaults to true in dev env
    # this is a temp fix until issue #141 at schmittjoh/JMSI18nRoutingBundle is fixed
    translator:
        logging: false

web_profiler:
    toolbar: true
    intercept_redirects: false
    excluded_ajax_paths:  /bundles|/_wdt

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true