parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     zikula
    database_user:     root
    database_password: ~
    database_path:     ~
    database_socket:   ~

    installed:        false
    compat_layer:     true
    temp_dir:         %kernel.cache_dir%/ztemp
    datadir:          userdata
    system.chmod_dir: 777

    display_pagerendertime: false

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
