parameters:
    installed:        false
    env:              dev
    debug:            true
    compat_layer:     true
    temp_dir:         %kernel.cache_dir%/ztemp
    datadir:          userdata
    system.chmod_dir: 0777

    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     ~
    database_user:     ~
    database_password: ~
    database_path:     ~
    database_socket:   ~

    pagerendertime:    false

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    url_secret:        ~
